version: 0.2

phases:
  
  install:
    runtime-versions:
      python: 3.8
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - pip3 install checkov     
  pre_build:
    commands:

  build:
    commands:
      - checkov -d resources --quiet
  post_build:
    commands:
      - echo terraform security review completed on `date`

artifacts:
  files:
    - 'resources/*'
  discard-paths: yes