version: 0.2

phases:
 
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform      
      - yum -y install jq
  pre_build:
    commands:
      #- aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/PoCAdmin --role-session-name poc
     - CREDENTIALS=$(aws sts assume-role --role-arn $TERRAFORM_ROLE --role-session-name terraform --duration-seconds 3600)
     - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
     - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
     - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
     - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')      
  build:
    commands:
      - cd resources
      - terraform init -backend-config="./backend.config"  
      - terraform plan --var-file=var.tfvars -out plan.out
      - terraform apply plan.out
  post_build:
    commands:
      - echo terraform configuration completed on `date`

artifacts:
  files:
    - 'resources/*'
  discard-paths: yes