version: 0.2

phases:
  install:
    commands:
      - echo "Source version" $CODEBUILD_RESOLVED_SOURCE_VERSION
      - aws --version
  build:
    commands:
       - aws lambda update-function-code --function-name ${function_name} --s3-key code.zip --s3-bucket ${code_bucket}
       - |
            state=$(aws lambda get-function --function-name ${function_name} | jq -r .Configuration.LastUpdateStatus) 
            echo "Current function update status:" $state 
            while [ "$state" != "Successful" ] 
            do 
                sleep 1 
                state=$(aws lambda get-function --function-name ${function_name} | jq -r .Configuration.LastUpdateStatus)  
                echo "Current status: " $state 
            done       
       - |-
          version=$(aws lambda publish-version --function-name ${function_name} --description "Commit : $CODEBUILD_RESOLVED_SOURCE_VERSION" | jq -r .Version)
       - echo "New version " $version
       - aws lambda update-alias --function-name ${function_name} --name test --function-version $version
       #
       # Some test required here
       #
       - |
          if [ "$TEST_URL" != "" ]
          then
            echo "Running test against URL " $TEST_URL
            status_code=$(curl --write-out %%{http_code} --silent --output /dev/null $TEST_URL)

            if [[ "$status_code" -ne 200 ]] 
            then
              echo "Site status changed to $status_code"
              exit 1
            else
              echo "Response status code " $status_code
            fi
          fi
       - aws lambda update-alias --function-name ${function_name} --name prod --function-version $version

       